
import { Language } from './types';

export const CATEGORIES = {
  income: ['Salary', 'Freelance', 'Investment', 'Gift', 'Other'],
  expense: ['Food', 'Transport', 'Housing', 'Utilities', 'Entertainment', 'Health', 'Education', 'Shopping', 'Savings', 'Other'],
  transfer: ['Transfer']
};

export const CURRENCIES = [
  { code: 'USD', label: 'USD - US Dollar', symbol: '$' },
  { code: 'SAR', label: 'SAR - Saudi Riyal', symbol: '﷼' },
  { code: 'AED', label: 'AED - UAE Dirham', symbol: 'د.إ' },
  { code: 'EGP', label: 'EGP - Egyptian Pound', symbol: '£' },
  { code: 'KWD', label: 'KWD - Kuwaiti Dinar', symbol: 'د.ك' },
  { code: 'QAR', label: 'QAR - Qatari Riyal', symbol: '﷼' },
  { code: 'EUR', label: 'EUR - Euro', symbol: '€' },
  { code: 'GBP', label: 'GBP - British Pound', symbol: '£' },
];

export const ENTITY_TYPES = {
  en: [
    { value: 'individual', label: 'Individual / Personal' },
    { value: 'company', label: 'Company' },
    { value: 'organization', label: 'Organization' },
    { value: 'institution', label: 'Institution' },
    { value: 'freelancer', label: 'Freelancer' },
    { value: 'store', label: 'Store / Shop' },
  ],
  ar: [
    { value: 'individual', label: 'فرد / شخصي' },
    { value: 'company', label: 'شركة' },
    { value: 'organization', label: 'منظمة' },
    { value: 'institution', label: 'مؤسسة' },
    { value: 'freelancer', label: 'مستقل' },
    { value: 'store', label: 'متجر / محل' },
  ]
};

export const WALLET_TYPES = {
  en: [
    { value: 'cash', label: 'Cash' },
    { value: 'bank', label: 'Bank Account' },
    { value: 'credit', label: 'Credit Card' },
    { value: 'other', label: 'Other' },
  ],
  ar: [
    { value: 'cash', label: 'نقدي (كاش)' },
    { value: 'bank', label: 'حساب بنكي' },
    { value: 'credit', label: 'بطاقة ائتمان' },
    { value: 'other', label: 'أخرى' },
  ]
};

export const TIPS = {
  en: [
    "Track every penny, even the small coffees.",
    "Save at least 20% of your income.",
    "Avoid impulse buying by waiting 24 hours.",
    "Review your subscriptions monthly.",
    "Set an emergency fund for 3-6 months."
  ],
  ar: [
    "تتبع كل قرش، حتى القهوة الصغيرة.",
    "ادخر ما لا يقل عن 20٪ من دخلك.",
    "تجنب الشراء المندفع بالانتظار 24 ساعة.",
    "راجع اشتراكاتك الشهرية بانتظام.",
    "ضع صندوق طوارئ يغطي 3-6 أشهر."
  ]
};

export const TRANSLATIONS = {
  en: {
    appTitle: "My Daily Accountant",
    welcome: "Welcome back,",
    signInTitle: "Sign in to manage your finances",
    signInGoogle: "Sign in with Google",
    demoLogin: "Try Demo Mode",
    dashboard: "Dashboard",
    analytics: "Analytics",
    income: "Income",
    expense: "Expense",
    balance: "Balance",
    recentTransactions: "Recent Transactions",
    addTransaction: "Add Transaction",
    editTransaction: "Edit Transaction",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    date: "Date",
    amount: "Amount",
    category: "Category",
    description: "Description",
    type: "Type",
    selectCategory: "Select Category",
    exportPDF: "Export PDF",
    exportCSV: "Export CSV",
    exportJSON: "Backup Data",
    importJSON: "Restore Data",
    statsOverview: "Statistics Overview",
    distribution: "Expenses Distribution",
    balanceHistory: "Balance History",
    monthlyComparison: "Monthly Income vs Expense",
    noTransactions: "No transactions yet.",
    confirmDelete: "Are you sure you want to delete this transaction?",
    tipOfTheDay: "Tip of the Day",
    logout: "Logout",
    total: "Total",
    settings: "Settings",
    budgetSettings: "Budget Settings",
    securitySettings: "Security",
    setPin: "Set App Lock PIN",
    pinPlaceholder: "Enter 4-digit PIN",
    enterPin: "Enter PIN to Unlock",
    pinError: "Incorrect PIN",
    enableNotifications: "Enable Notifications",
    notificationsEnabled: "Notifications Enabled",
    notificationsDisabled: "Notifications Disabled",
    setBudget: "Set Monthly Limit",
    budgetAlert: "Budget Alert",
    budgetExceeded: "Budget Exceeded",
    nearLimitMsg: "You have used 80% of your budget for",
    overLimitMsg: "You have exceeded your budget for",
    setupTitle: "Account Setup",
    setupSubtitle: "Please provide a few details to customize your experience.",
    entityName: "Entity Name (e.g. My Company)",
    entityType: "Entity Type",
    currency: "Currency",
    completeSetup: "Complete Setup",
    invalidAmount: "Please enter a valid positive amount.",
    categoryRequired: "Please select a category.",
    developedBy: "Developed by Mohamed Ahmed",
    scanReceipt: "Scan Receipt with AI",
    scanning: "Analyzing Receipt...",
    recurrence: "Recurrence",
    none: "None",
    daily: "Daily",
    weekly: "Weekly",
    monthly: "Monthly",
    recurrenceInfo: "This transaction will repeat automatically.",
    wallets: "Wallets",
    addWallet: "Add Wallet",
    walletName: "Wallet Name",
    initialBalance: "Initial Balance",
    transfer: "Transfer",
    fromWallet: "From Wallet",
    toWallet: "To Wallet",
    goals: "Savings Goals",
    addGoal: "Add Goal",
    goalName: "Goal Name",
    targetAmount: "Target Amount",
    currentAmount: "Current Amount",
    deposit: "Deposit",
    withdraw: "Withdraw",
    goalReached: "Goal Reached!",
    selectWallet: "Select Wallet",
    insufficientFunds: "Insufficient funds in selected wallet.",
    addFundsToGoal: "Add Funds to Goal",
    depositAmount: "Deposit Amount",
  },
  ar: {
    appTitle: "محاسبي اليومي",
    welcome: "أهلاً بك،",
    signInTitle: "سجل الدخول لإدارة أموالك",
    signInGoogle: "تسجيل الدخول عبر جوجل",
    demoLogin: "تجربة النسخة التجريبية",
    dashboard: "لوحة التحكم",
    analytics: "التحليلات",
    income: "الدخل",
    expense: "المصاريف",
    balance: "الرصيد",
    recentTransactions: "أحدث المعاملات",
    addTransaction: "إضافة معاملة",
    editTransaction: "تعديل المعاملة",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    date: "التاريخ",
    amount: "المبلغ",
    category: "التصنيف",
    description: "الوصف",
    type: "النوع",
    selectCategory: "اختر التصنيف",
    exportPDF: "تصدير تقرير PDF",
    exportCSV: "تصدير Excel/CSV",
    exportJSON: "نسخ احتياطي",
    importJSON: "استعادة البيانات",
    statsOverview: "نظرة عامة",
    distribution: "توزيع المصاريف",
    balanceHistory: "تطور الرصيد",
    monthlyComparison: "مقارنة الدخل والمصاريف",
    noTransactions: "لا توجد معاملات بعد.",
    confirmDelete: "هل أنت متأكد من حذف هذه المعاملة؟",
    tipOfTheDay: "نصيحة اليوم",
    logout: "تسجيل خروج",
    total: "الإجمالي",
    settings: "الإعدادات",
    budgetSettings: "إعدادات الميزانية",
    securitySettings: "الأمان",
    setPin: "تعيين رمز قفل التطبيق",
    pinPlaceholder: "أدخل رمز مكون من 4 أرقام",
    enterPin: "أدخل الرمز لفتح التطبيق",
    pinError: "الرمز غير صحيح",
    enableNotifications: "تفعيل الإشعارات",
    notificationsEnabled: "الإشعارات مفعلة",
    notificationsDisabled: "الإشعارات غير مفعلة",
    setBudget: "تحديد الحد الشهري",
    budgetAlert: "تنبيه الميزانية",
    budgetExceeded: "تجاوز الميزانية",
    nearLimitMsg: "لقد استهلكت 80% من ميزانية",
    overLimitMsg: "لقد تجاوزت ميزانية",
    setupTitle: "إعداد الحساب",
    setupSubtitle: "يرجى تقديم بعض التفاصيل لتخصيص تجربتك.",
    entityName: "اسم الجهة (مثلاً: شركتي)",
    entityType: "نوع الجهة",
    currency: "العملة",
    completeSetup: "إكمال الإعداد",
    invalidAmount: "يرجى إدخال مبلغ صحيح.",
    categoryRequired: "يرجى اختيار تصنيف.",
    developedBy: "تم التطوير بواسطة محمد أحمد",
    scanReceipt: "مسح الإيصال بالذكاء الاصطناعي",
    scanning: "جاري تحليل الإيصال...",
    recurrence: "التكرار",
    none: "لا يوجد",
    daily: "يومي",
    weekly: "أسبوعي",
    monthly: "شهري",
    recurrenceInfo: "سيتم تكرار هذه المعاملة تلقائياً.",
    wallets: "المحافظ",
    addWallet: "إضافة محفظة",
    walletName: "اسم المحفظة",
    initialBalance: "الرصيد الافتتاحي",
    transfer: "تحويل",
    fromWallet: "من محفظة",
    toWallet: "إلى محفظة",
    goals: "أهداف الادخار",
    addGoal: "إضافة هدف",
    goalName: "اسم الهدف",
    targetAmount: "المبلغ المستهدف",
    currentAmount: "المبلغ الحالي",
    deposit: "إيداع",
    withdraw: "سحب",
    goalReached: "تحقق الهدف!",
    selectWallet: "اختر المحفظة",
    insufficientFunds: "رصيد غير كافٍ في المحفظة المختارة.",
    addFundsToGoal: "إيداع في الهدف",
    depositAmount: "مبلغ الإيداع",
  }
};

export const formatCurrency = (amount: number, currencyCode: string = 'USD', lang: Language) => {
  return new Intl.NumberFormat(lang === 'ar' ? 'ar-SA' : 'en-US', {
    style: 'currency',
    currency: currencyCode, 
  }).format(amount);
};
